### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by democat3457**
Fixes the jar breaking if the old loading events were removed by updating the CraftTweaker build
(Reference https://canary.discord.com/channels/136877912698650625/827789353467117569/829389364323680287 and below)

(also please make this at least a beta build so we can include this in modpacks)

### CODE REVIEW

**Comment by Darkhax** [comment]
I am not set up to publish 1.12 builds right now. Forge also moved a lot of stuff around so there are some needed infrastructure changes. I might consider this, but 1.12 is not a supported version.

**Comment by democat3457** [comment]
I see, rip

Also reeeee forge

**Comment by Darkhax** [comment]
I've merged your changes but like I said previously we're not set up for publishing 1.12 anymore and it likely won't be. People can still build from master though.

**Comment by democat3457** [comment]
Alright, cool

**Pull request merged**
